#!/usr/bin/env bash
#
# Generate the Antigravity plugin package from the canonical Claude Code one.
#
# Usage:
#   scripts/sync-antigravity-plugin.sh           # regenerate the package
#   scripts/sync-antigravity-plugin.sh --check   # fail if it is out of date
#
# Why this exists:
#   Claude Code and Antigravity both read `agents/` and `skills/` from a plugin
#   directory, but they disagree on what belongs in the frontmatter. Claude Code
#   wants `tools:` and `model:`; Antigravity maps tool names against its own
#   registry, where an unmapped name can hang the subagent. The two hosts cannot
#   share one directory, so the Antigravity package is generated from the
#   canonical one and committed alongside it.
#
# The transform:
#   agents/*.md    -> agents/*.md          frontmatter: drop tools/model, add subagent
#   commands/*.md  -> skills/<name>/SKILL.md
#   .agents/AGENTIC_DEV_TEAM.md -> rules/agentic-dev-team.md
#   AGENTIC_DEV_TEAM_PIPELINE.md -> AGENTIC_DEV_TEAM_PIPELINE.md
#   .claude-plugin/plugin.json   -> plugin.json (Antigravity manifest location)
#
#   In every body, ${CLAUDE_PLUGIN_ROOT} becomes the path Antigravity stages a
#   plugin to, so the "plugin-only install" fallbacks resolve under `agy`.

set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$REPO_DIR/plugins/agentic-dev-team"
DEST="$REPO_DIR/plugins/agentic-dev-team-antigravity"
PERSONAS="$REPO_DIR/.agents/AGENTIC_DEV_TEAM.md"

# Where `agy plugin install` stages this package. The commands and agents fall
# back to it when a project has no install.sh-created .claude/ directory.
AGY_PLUGIN_ROOT='~/.gemini/antigravity-cli/plugins/agentic-dev-team'

GENERATED_NOTE='<!-- Generated by scripts/sync-antigravity-plugin.sh — do not edit by hand.
     Edit the canonical file under plugins/agentic-dev-team/ and re-run the script. -->'

MODE="write"
for arg in "$@"; do
  case "$arg" in
    --check) MODE="check" ;;
    -h|--help) sed -n '2,/^set -euo/p' "${BASH_SOURCE[0]}" | sed 's/^#//'; exit 0 ;;
    *) echo "Unknown flag: $arg" >&2; exit 2 ;;
  esac
done

# ---------- helpers ----------

# Rewrite Claude-only path variables for the Antigravity staging location.
# Reads stdin, writes stdout.
retarget_paths() {
  sed "s|\${CLAUDE_PLUGIN_ROOT}|$AGY_PLUGIN_ROOT|g"
}

# Emit a file's YAML frontmatter, dropping the top-level keys named in $1
# (a '|'-separated list) and appending the extra lines in $2.
#
# Continuation lines of a folded scalar are indented, so matching dropped keys
# at column 0 leaves multi-line `description: >` blocks intact.
rewrite_frontmatter() {
  local file="$1" drop="$2" extra="${3:-}"
  awk -v drop="$drop" -v extra="$extra" '
    NR == 1 && $0 == "---" { print; next }
    $0 == "---" {
      if (extra != "") print extra
      print
      exit
    }
    {
      # A top-level key starts at column 0 and looks like `key:`.
      if (match($0, /^[A-Za-z_-]+:/)) {
        key = substr($0, 1, RLENGTH - 1)
        dropping = (drop != "" && key ~ "^(" drop ")$")
      }
      if (!dropping) print
    }
  ' "$file"
}

# Everything after the closing --- of the frontmatter.
body_of() {
  awk 'BEGIN{n=0} /^---$/ && n<2 {n++; next} n>=2 {print}' "$1"
}

# ---------- generation ----------

build_into() {
  local out="$1"
  local f name

  mkdir -p "$out/agents" "$out/skills" "$out/rules"

  # plugin.json — Antigravity reads the manifest from the plugin root, not from
  # a .claude-plugin/ subdirectory. Values are carried over from the canonical
  # manifest so the two never describe the plugin differently.
  local desc author homepage repo license
  desc="$(sed -n 's/.*"description"[[:space:]]*:[[:space:]]*"\(.*\)".*/\1/p' "$SRC/.claude-plugin/plugin.json" | head -1)"
  author="$(sed -n 's/.*"author"[[:space:]]*:[[:space:]]*{[[:space:]]*"name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$SRC/.claude-plugin/plugin.json" | head -1)"
  homepage="$(sed -n 's/.*"homepage"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$SRC/.claude-plugin/plugin.json" | head -1)"
  repo="$(sed -n 's/.*"repository"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$SRC/.claude-plugin/plugin.json" | head -1)"
  license="$(sed -n 's/.*"license"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$SRC/.claude-plugin/plugin.json" | head -1)"

  cat > "$out/plugin.json" <<JSON
{
  "\$schema": "https://antigravity.google/schemas/v1/plugin.json",
  "name": "agentic-dev-team",
  "description": "$desc",
  "author": { "name": "$author" },
  "homepage": "$homepage",
  "repository": "$repo",
  "license": "$license"
}
JSON

  # Agents. Antigravity resolves `tools:` against its own registry and an
  # unmapped name can hang the subagent, so the list is dropped — omitting it
  # gives the subagent the host's default toolset. `model:` is dropped too:
  # Antigravity has no per-subagent model selection and every subagent inherits
  # the user's globally selected model.
  for f in "$SRC"/agents/*.md; do
    name="$(basename "$f")"
    {
      rewrite_frontmatter "$f" 'tools|model' 'subagent: true'
      printf '\n%s\n' "$GENERATED_NOTE"
      body_of "$f"
    } | retarget_paths > "$out/agents/$name"
  done

  # Commands become skills. Antigravity has no `commands/` concept — a skill is
  # what surfaces as a slash command, so /build-auto and friends live here.
  for f in "$SRC"/commands/*.md; do
    name="$(basename "$f" .md)"
    mkdir -p "$out/skills/$name"
    {
      rewrite_frontmatter "$f" '' ''
      printf '\n%s\n' "$GENERATED_NOTE"
      body_of "$f"
    } | retarget_paths > "$out/skills/$name/SKILL.md"
  done

  # Personas as always-on rules. This is the same content install.sh inlines
  # into a project's .agents/agents.md, which is where Antigravity picks up
  # user rules — shipping it as a plugin rule makes install.sh optional.
  #
  # This copy is only ever read when the plugin is installed, so `.claude/agents/`
  # never resolves for it: install.sh inlines the canonical .agents/ file instead
  # of this one. Point the persona prompts at the staged plugin directory.
  {
    printf '%s\n\n' "$GENERATED_NOTE"
    cat "$PERSONAS"
  } | retarget_paths \
    | sed "s|\`\.claude/agents/|\`$AGY_PLUGIN_ROOT/agents/|g" \
    > "$out/rules/agentic-dev-team.md"

  # Shared orchestration rules, referenced by every agent and skill.
  {
    printf '%s\n\n' "$GENERATED_NOTE"
    cat "$SRC/AGENTIC_DEV_TEAM_PIPELINE.md"
  } | retarget_paths > "$out/AGENTIC_DEV_TEAM_PIPELINE.md"
}

# ---------- main ----------

case "$MODE" in
  write)
    rm -rf "$DEST"
    build_into "$DEST"
    echo "Generated $(basename "$DEST") from $(basename "$SRC"):"
    echo "  agents: $(find "$DEST/agents" -name '*.md' | wc -l | tr -d ' ')"
    echo "  skills: $(find "$DEST/skills" -name 'SKILL.md' | wc -l | tr -d ' ')"
    echo "  rules:  $(find "$DEST/rules" -name '*.md' | wc -l | tr -d ' ')"
    ;;
  check)
    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' EXIT
    build_into "$tmp/pkg"
    if diff -ru "$DEST" "$tmp/pkg" > "$tmp/diff" 2>&1; then
      echo "Antigravity package is up to date."
    else
      echo "Antigravity package is out of date. Run scripts/sync-antigravity-plugin.sh" >&2
      echo "" >&2
      cat "$tmp/diff" >&2
      exit 1
    fi
    ;;
esac
